name 'chef_postfix_redis'
maintainer 'burtininkai'
maintainer_email 'marijus.ravickas@gmail.com'
license 'MIT'
description 'Installs/Configures chef_postfix_redis'
long_description 'Installs/Configures chef_postfix_redis'
version '0.1.0'
chef_version '>= 13.0'
issues_url 'https://github.com/burtininkai/chef_postfix_redis/issues'
source_url 'https://github.com/burtininkai/chef_postfix_redis'
supports 'centos'
depends 'postfix'
